image: python:3.5.1

pipelines:
  default:
    - step:
        script:
          - pip install -r backend/requirements.txt
          - cd backend/pact/ && ./manage.py test
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      variables: 
        POSTGRES_DB: 'pact' 
        POSTGRES_USER: 'pact'
        POSTGRES_PASSWORD: 'pact'
