version: "3.9"
services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pact-backend
    volumes:
      - ./backend:/app
    command: >
      bash -c 'while !</dev/tcp/database/5432; do sleep 1; done
      && pipenv run manage migrate
      && pipenv run manage runserver 0.0.0.0:8000'
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - SECRET_KEY="not-a-very-secret-key"
    ports:
      - "8081:8000"
    expose:
      - 8000

  vue:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.vuejs-dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vue.config.js:/app/vue.config.js
      - ./frontend/babel.config.js:/app/babel.config.js
    ports:
      - "8080:8080"

  database:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data: