version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pact-backend
    restart: unless-stopped
    command: >
      bash -c 'while !</dev/tcp/database/5432; do sleep 1; done
      && .venv/bin/python3 pact/manage.py migrate
      && .venv/bin/python3 -m gunicorn --config /app/gunicorn_config.py pact.wsgi:application'
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - SECRET_KEY="not-a-very-secret-key"
    expose:
      - 8000

  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web-server
    ports:
      - "8080:80"

  database:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  postgres_data: