# Generated by Django 2.2 on 2019-04-21 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=8192)),
                ('hit_dice', models.CharField(blank=True, default='', max_length=128)),
                ('is_player', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, default='', max_length=8192)),
                ('current_initiative', models.IntegerField(blank=True, null=True)),
                ('current_round', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterCharacter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('initiative', models.IntegerField(null=True)),
                ('max_hp', models.IntegerField(null=True)),
                ('current_hp', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=128)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Encounter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('remaining_duration', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.EncounterCharacter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='characters',
            field=models.ManyToManyField(through='manager.EncounterCharacter', to='manager.Character'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
