# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160501_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('remaining_duration', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.EncounterCharacter')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_dice',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
