# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def generate_uuid(model_name):
    def inner(apps, schema_editor):
        model = apps.get_model('manager', model_name)
        for m in model.objects.all():
            m.uuid = uuid.uuid4()
            m.save()
    return inner


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20160514_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(
                default=None,
                null=True,
                editable=False,
                unique=False
            ),
        ),
        migrations.AddField(
            model_name='encounter',
            name='uuid',
            field=models.UUIDField(
                default=None,
                null=True,
                editable=False,
                unique=False
            ),
        ),
        migrations.AddField(
            model_name='encountercharacter',
            name='uuid',
            field=models.UUIDField(
                default=None,
                null=True,
                editable=False,
                unique=False
            ),
        ),
        migrations.AddField(
            model_name='statuseffect',
            name='uuid',
            field=models.UUIDField(
                default=None,
                null=True,
                editable=False,
                unique=False
            ),
        ),
        migrations.RunPython(
            generate_uuid('character'),
        ),
        migrations.RunPython(
            generate_uuid('encounter'),
        ),
        migrations.RunPython(
            generate_uuid('encountercharacter'),
        ),
        migrations.RunPython(
            generate_uuid('statuseffect'),
        ),
        migrations.AlterField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True
            ),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True
            ),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='encountercharacter',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True
            ),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True
            ),
            preserve_default=True,
        ),
    ]
