# Generated by Django 3.2.8 on 2021-10-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_fiftheditionmonster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindermonster',
            name='classes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pathfindermonster',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
