# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20160731_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='encountercharacter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='statuseffect',
            name='id',
        ),
        migrations.AlterField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='encountercharacter',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
