# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_encounter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='speed_stat',
            field=models.IntegerField(default=None, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='current_speed_stat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
