# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=8192)),
                ('hit_dice', models.CharField(max_length=128, null=True)),
                ('is_player', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=256)),
                ('current_initiative', models.IntegerField(null=True)),
                ('current_round', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('initiative', models.IntegerField(null=True)),
                ('max_hp', models.IntegerField(null=True)),
                ('current_hp', models.IntegerField(null=True)),
                ('notes', models.CharField(default='', max_length=128)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Encounter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='characters',
            field=models.ManyToManyField(through='manager.EncounterCharacter', to='manager.Character'),
        ),
    ]
