# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='current_initiative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encountercharacter',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
