# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_created_by(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Character = apps.get_model('manager', 'character')
    Encounter = apps.get_model('manager', 'encounter')
    Character.objects.all().update(created_by=User.objects.last())
    Encounter.objects.all().update(created_by=User.objects.last())


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0005_auto_20160731_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_by),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
