# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20160804_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=8192),
        ),
    ]
