name: Django CI

on:
  push:
    branches: [ test-actions ]
  pull_request:
    branches: [ test-actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10.0-alpha.1' ]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: backend
      run: |
        python -m pip install pipenv
        pipenv sync
    - name: Run Tests
      working-directory: backend
      run: |
        pipenv run manage test
